sudo: required

language: go

services:
  - docker

go:
  - '1.9'

script:
- make clean

deploy:
  - provider: script
    script: bash docker_push latest
    on:
      branch: master
  - provider: script
    script: bash docker_push $TRAVIS_TAG
    on:
      tags: true
